### PR TITLE
added VuePress docs

### PR DESCRIPTION
**Pull request by christianmalek**

### CODE REVIEW

**Comment by ghenry** [comment]
Nice work!!! Do you have a domain name for the site?

**Comment by christianmalek** [comment]
At the moment not. I'm still figuring out how to use github pages.

**Comment by ghenry** [comment]
We're using this in the SureVoIP Portal. If you'd like a donation of a domain name, let me know what you'd like. Docs look great!
screenshot_2018-08-13 api vuex-rest-api

**Comment by christianmalek** [comment]
@ghenry If you want to donate a domain name I would appreciate it. But it's not really necessary. I've just pushed it to the `gh-pages` branch. You can access it here: https://christianmalek.github.io/vuex-rest-api/

Please note that this is just the README and the CHANGELOG at the moment. I will update it when I'm releasing version 3 of vuex-rest-api.

**Comment by christianmalek** [comment]
@ghenry This is very generous of you. I would prefer the following domain name `vuex-rest-api.org`

**Comment by ghenry** [comment]
Done. I've forwarded it to the GitHub url for now. It's on godaddy. Let me
know if you need it transferred. Valid for 2 years.

**Comment by christianmalek** [comment]
@ghenry Wow. Thank you very much! I really appreciate it.

**Comment by ghenry** [comment]
It's nothing really for what you've written!

**Comment by christianmalek** [comment]
@ghenry How complicated would it be to transfer the domain?

**Comment by ghenry** [comment]
Not complicated at all.

--
Kind Regards,

Gavin Henry.
Managing Director.

T +44 (0) 330 44 50 000
D +44 (0) 330 44 55 007
M +44 (0) 7930 323266
F +44 (0) 1224 824887
E ghenry@suretec.co.uk

Open Source. Open Solutions(tm).

http://www.suretecsystems.com/

Winner of the Best Business ITSP (Medium Enterprise) 2016!
http://www.surevoip.co.uk/2016-best-provider

Suretec Systems is a limited company registered in Scotland. Registered
number: SC258005. Registered office: 24 Cormack Park, Rothienorman,
Inverurie, Aberdeenshire, AB51 8GL.

Subject to disclaimer at http://www.suretecgroup.com/disclaimer.html

Do you know we have our own VoIP provider called SureVoIP? See
http://www.surevoip.co.uk

OpenPGP (GPG/PGP) Public Key: 0x8CFBA8E6 - Import from hkp://
pool.subkeys.pgp.net
or http://www.suretecgroup.com/0x8CFBA8E6.gpg

**Pull request merged**
