### PR TITLE
update version of axios

### LINKED ISSUE #96: Update peer dependency of axios
It might be an idea to update the peer dependency of axios to include `^0.19`

### PR DESCRIPTION
**Pull request by ilyaryabchinski**
closes #96

### CODE REVIEW

**Comment by christianmalek** [comment]
Thanks! I'll merge your PR this weekend so that I can also update the npm package.

**Comment by ilyaryabchinski** [comment]
Awesome! Thank you too!

**Comment by christianmalek** [comment]
I'll do it next week. Sorry, didn't find time to do it yet.

**Comment by ilyaryabchinski** [comment]
Okay. Will wait for it. I'm just afraid that this PR will not be counted by hacktoberfest challenge.

**Comment by christianmalek** [comment]
@ilyaryabchinski It will. You can look it up on https://hacktoberfest.digitalocean.com/profile
PRs have not to be merged. They count also unmerged.

**Comment by ilyaryabchinski** [comment]
@christianmalek yeah, thanks for the info 😄

**Pull request merged**
